### ISSUE TITLE
larseggert/iana-assignments

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/iana-registries#1]
https://github.com/larseggert/iana-assignments has a lot more history whcih you could merge here.

**Comment by ronaldtse** [comment]
Thanks @larseggert for the suggestion, happy to replace existing history with yours as it goes back to 2015.

**Comment by ronaldtse** [comment]
Imported via rebase. Inserted our initial commit on 2021-08-20 (a73baa1d0fb482948cb998ff00083c5b1555778e) and added date to future commits in ietf-ribose/iana-registries-sync#2 albeit the date format is slightly different.
